---
  - name: Update all packages on Dev servers
    hosts: dev
    gather_facts: yes
    tasks:
      - name: Update CentOS
        when: ansible_facts['distribution'] == "CentOS"
        yum:
          name: '*'
          state: latest

      - name: Update Ubuntu
        when: ansible_facts['distribution'] == "Ubuntu"
        apt:
          name: '*'
          state: latest